spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kcalculator?characterEncoding=UTF-8
    username: kcalculator
    password: +jG{ZzjCF_Ph6xT
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
mybatis:
  mapper-locations: mappers/*Mapper.xml